// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACxgEw9vc6wbkH18CSZZu-YCD3ZRNHsi8',
    appId: '1:1094187348595:android:a34a5219107678b220f006',
    messagingSenderId: '1094187348595',
    projectId: 'boton-de-emergencia-emsad',
    storageBucket: 'boton-de-emergencia-emsad.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUSRGYYYa_A5GqfP6VYwSmY4jVVWyFd3k',
    appId: '1:1094187348595:ios:1ecd985353bd1a0b20f006',
    messagingSenderId: '1094187348595',
    projectId: 'boton-de-emergencia-emsad',
    storageBucket: 'boton-de-emergencia-emsad.firebasestorage.app',
    androidClientId: '1094187348595-g8vas8shitac0dsrn9d2hlvl1h6h1fe7.apps.googleusercontent.com',
    iosClientId: '1094187348595-nd47eok68mqi9ohcg5mo3tnmvl6n1ro1.apps.googleusercontent.com',
    iosBundleId: 'teckali.com.botonDeEmergencia',
  );
}
